import React from 'react'

function App() {
  return (
    <div style={{ padding: '2rem', fontFamily: 'system-ui' }}>
      <h1>🚀 Vibe Coder Workflow Test</h1>
      <p>This is a test deployment from the complete workflow system.</p>
      <div style={{ marginTop: '2rem', padding: '1rem', background: '#f0f0f0', borderRadius: '8px' }}>
        <h3>Deployment Features Tested:</h3>
        <ul>
          <li>✅ GitHub repository creation</li>
          <li>✅ Code push to GitHub</li>
          <li>⏳ Vercel project creation (manual connection needed)</li>
          <li>⏳ Live preview URL retrieval</li>
        </ul>
      </div>
      <p style={{ marginTop: '2rem', fontSize: '0.9em', color: '#666' }}>
        Generated by Vibe Coder deployment system
      </p>
    </div>
  )
}

export default App